#!/system/bin/sh
echo 62 > /proc/overclock/max_vsel
echo 4 1200000000 62 > /proc/overclock/mpu_opps
echo 3 800000000 42 > /proc/overclock/mpu_opps
echo 2 600000000 32 > /proc/overclock/mpu_opps
echo 1 300000000 17 > /proc/overclock/mpu_opps
echo 0 1200000 > /proc/overclock/freq_table
echo 1 800000 > /proc/overclock/freq_table
echo 2 600000 > /proc/overclock/freq_table
echo 3 300000 > /proc/overclock/freq_table
echo 1200000 > /proc/overclock/max_rate
echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 266666666 > /proc/gpu/max_rate
echo noop > /sys/block/mmcblk0/queue/scheduler
echo noop > /sys/block/mmcblk1/queue/scheduler
sleep 50
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
